feat: add utm fields in orders
GetSimpl/simpl-checkout-woocommerce pull request #101
Opened 2023-09-11 19:29 UTC by abhaymaniyar

2023-09-13 06:42 UTC, rithiksharma100 requested changes

2023-09-13 06:42 UTC, rithiksharma100 commented on tests/simpl/test-checkout-endpoint.php
> +        print_r($response_data);
cleanup

2023-09-13 06:42 UTC, rithiksharma100 commented on tests/simpl/test-checkout-endpoint.php
> +        print_r($response_data);
cleanup

2023-09-13 06:42 UTC, rithiksharma100 commented on includes/simpl_integration/class-cart-response.php
> +        $response["merchant_additional_details"] = $merchant_additional_details;
where is this variable `$merchant_additional_details` assigned?

2023-09-13 06:42 UTC, rithiksharma100 commented on simpl-checkout-woocommerce.php
> + * Version: 1.1.3
update the branch with `main` once, this isn't the latest version

2023-09-13 06:42 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +    static function set_utm_info_in_order($request, $order) {
we can write a loop for this as done in `checkout-api` instead of using the same hardcoded strings again and again

2023-09-13 06:42 UTC, rithiksharma100 commented on includes/simpl_integration/class-cart-response.php
> +        $response["merchant_additional_details"] = $merchant_additional_details;
we can include this in the cart object itself, it will reduce the checkout-3pp changes

2023-09-13 10:22 UTC, abhaymaniyar commented on includes/simpl_integration/class-cart-response.php
> +        $response["merchant_additional_details"] = $merchant_additional_details;
fair point. removed.

2023-09-13 10:22 UTC, abhaymaniyar commented on includes/simpl_integration/class-cart-response.php
> +        $response["merchant_additional_details"] = $merchant_additional_details;
fair. added.

2023-09-13 10:22 UTC, abhaymaniyar commented on simpl-checkout-woocommerce.php
> + * Version: 1.1.3
1.1.2 is the latest version. Updating it to 1.1.3.

2023-09-14 06:43 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +    static function set_utm_info_in_order($request, $order) {
I'm referring to the `checkout-api` code where _landing_page, utm_medium, fbclid, etc are defined as a string of constants and we simply just loop through them

2023-09-14 06:58 UTC, rithiksharma100 requested changes
Is it clarified that we only want UTM info for completed orders, and not for drafts or abandoned checkouts?
@abhaymaniyar @piyush-getsimpl

2023-09-14 06:58 UTC, rithiksharma100 commented on includes/simpl_integration/class-cart-response.php
> +        $cart_payload = $this->cart_common_payload($cart, $merchant_additional_details);
Use of unassigned variable `$merchant_additional_details`

2023-09-14 09:52 UTC, rithiksharma100 approved these changes

2023-09-18 08:11 UTC, merged