In-house Shipping
GetSimpl/simpl-checkout-woocommerce pull request #110
Opened 2023-09-21 17:17 UTC by rithiksharma100

2023-09-25 07:15 UTC, piyush-getsimpl commented on includes/endpoints/internal/class-simpl-checkout-order-controller.php
> -    protected function update_order_metadata($request, $order)
Lets use simpl_ prefix for all the functions/class we create going forward

2023-09-25 07:15 UTC, piyush-getsimpl commented on includes/endpoints/internal/class-simpl-checkout-order-controller.php
> +    static function update_order_details($request, $order) {
Lets use simpl_ prefix for all the functions/class we create going forward

2023-09-25 07:15 UTC, piyush-getsimpl commented on includes/helpers/class-simpl-wc-helper.php
> +    static function update_order_metadata($request, $order)
simpl_update_order_metadata

2023-09-25 07:16 UTC, piyush-getsimpl commented on includes/helpers/class-simpl-wc-helper.php
> +    static protected function set_utm_info_in_order($request, $order) {
simpl_set_utm_info_in_order

2023-09-25 07:16 UTC, piyush-getsimpl commented on includes/helpers/class-simpl-wc-helper.php
> +    static function set_shipping_method_in_order($order, $shipping_method) {
simpl_set_shipping_method_in_order

2023-09-25 08:33 UTC, rithiksharma100 commented on includes/endpoints/internal/class-simpl-checkout-order-controller.php
> +    static function update_order_details($request, $order) {
done

2023-09-25 08:33 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +    static function update_order_metadata($request, $order)
done

2023-09-25 08:33 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +    static protected function set_utm_info_in_order($request, $order) {
done

2023-09-25 08:33 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +    static function set_shipping_method_in_order($order, $shipping_method) {
done

2023-09-26 06:09 UTC, sathia27 requested changes

2023-09-26 06:09 UTC, sathia27 commented on simpl-checkout-woocommerce.php
> +    add_filter( 'woocommerce_shipping_chosen_method', '__return_false', 99); // this disables the application of default shipping method
Could this potentially create problems for the merchant? For instance, if our plugin, once installed, disables WooCommerce's shipping functionality, what happens when a customer want to use native woocommerce?

2023-09-26 06:11 UTC, rithiksharma100 commented on simpl-checkout-woocommerce.php
> +    add_filter( 'woocommerce_shipping_chosen_method', '__return_false', 99); // this disables the application of default shipping method
@sathia27 I tested this out on our staging store, the only change that happens is that the default shipping method is not selected in the native flow, so customers will have to select one manually

2023-09-26 06:12 UTC, rithiksharma100 commented on simpl-checkout-woocommerce.php
> +    add_filter( 'woocommerce_shipping_chosen_method', '__return_false', 99); // this disables the application of default shipping method
i'll do prod sanity as well on our prod store before installing this with merchants

2023-09-26 06:32 UTC, sathia27 requested changes

2023-09-26 06:32 UTC, sathia27 commented on includes/helpers/class-simpl-wc-helper.php
> +    static function simpl_update_order_metadata($request, $order)
we are planning to go public, let's start writing tests for plugin.

2023-09-26 06:39 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +    static function simpl_update_order_metadata($request, $order)
sure

2023-10-03 05:59 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +    static function simpl_update_order_metadata($request, $order)
discussed with @piyush-getsimpl, it's taking a lot of time to write test cases, so I'll release the test cases in a subsequent PR

2023-10-03 06:13 UTC, sathia27 requested changes

2023-10-03 06:13 UTC, sathia27 commented on includes/helpers/class-simpl-wc-helper.php
> +        if ($request->get_params()["simpl_payment_type"] == 'Cash on Delivery (COD)') {
Can you move these to constant `Cash on Delivery (COD)`

2023-10-03 06:13 UTC, sathia27 commented on includes/helpers/class-simpl-wc-helper.php
> +            $order->set_payment_method('Simpl Checkout');
this also can move to constant. This is right time to fix these existing issues.

2023-10-03 07:13 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +            $order->set_payment_method('Simpl Checkout');
done

2023-10-03 09:22 UTC, sathia27 submitted a review, later dismissed

2023-10-04 14:47 UTC, sathia27 approved these changes

2023-10-05 09:20 UTC, merged