added controller for ajax cart
GetSimpl/simpl-checkout-woocommerce pull request #120
Opened 2023-10-09 10:29 UTC by SimplTanishq

2023-10-09 12:19 UTC, abhaymaniyar requested changes

2023-10-09 12:19 UTC, abhaymaniyar commented on includes/admin/class-simpl-checkout-settings.php
> +		return 'shop.1bill.in';
Was this hardcoded only for testing purpose? If yes, please remove. If not, please explain why.

2023-10-09 17:30 UTC, Chhekur commented on includes/widget/buy-now-button.php
> +if(WC_Simpl_Settings::can_display_in_mini_cart()){
should this be can or should?

2023-10-09 17:30 UTC, Chhekur commented on includes/widget/buy-now-button.php
> +function simpl_enable_cta_in_mini_cart() {
this single method is doing a lot of things, can be divided into multiple small reusable methods.

2023-10-09 17:30 UTC, Chhekur commented on includes/widget/buy-now-button.php
> +    echo '</script>';
```php
$button_script = <<<SCRIPT
<script>
document.addEventListener("DOMContentLoaded", function() {
  var dataElement = document.createElement("div");
  dataElement.id = "simpl-custom-data";
  dataElement.setAttribute("data-is-mini-cart-cta-enabled", "true");
  document.head.appendChild(dataElement);
});
</script>
SCRIPT;

echo $button_script;
```

2023-10-11 08:54 UTC, rithiksharma100 requested changes

2023-10-11 08:54 UTC, rithiksharma100 commented on includes/widget/set-plugin-config.php
> +		echo( '<script type="text/javascript">var SimplPluginConfig = ' . json_encode($simpl_plugin_settings) . '</script>' );
this is against the Wordpress guidelines for publishing our plugin, there is a native method to include scripts, we shouldn't do it using `echo`

2023-10-11 11:13 UTC, SimplTanishq commented on includes/widget/buy-now-button.php
> +if(WC_Simpl_Settings::can_display_in_mini_cart()){
following previous patterns of naming, other setting functions are named similarly

2023-10-12 09:51 UTC, Chhekur submitted a review, later dismissed

2023-10-12 09:55 UTC, rithiksharma100 approved these changes

2023-10-16 06:45 UTC, rithiksharma100 approved these changes

2023-10-16 06:48 UTC, Chhekur approved these changes

2023-10-16 07:09 UTC, abhaymaniyar approved these changes

2023-10-16 07:15 UTC, merged