serve widget script over http2
GetSimpl/simpl-checkout-woocommerce pull request #134
Opened 2023-10-19 11:38 UTC by piyush-getsimpl

2023-10-20 16:09 UTC, piyush-getsimpl commented on includes/helpers/script_helper.php
> +  		$attrs = ' ';
`$attrs =  implode(" ", SCRIPT_ATTRIBUTES);`

2023-10-20 16:26 UTC, piyush-getsimpl commented on includes/widget/buy-now-button.php
> +  simpl_inject_script('<script {{attributes}} type="text/javascript" src=' .$script_url. '></script>');
`echo sprintf('<script %s type="text/javascript" src=%s></script>',  implode(" ", SCRIPT_ATTRIBUTES), $script_url);`

Something of this sort can also be done - still need to uncomplicate it.

2023-10-22 05:48 UTC, Chhekur commented on includes/widget/buy-now-button.php
> +  simpl_inject_script('<script {{attributes}} type="text/javascript" src=' .$script_url. '></script>');
agree,  but I was thinking the same but I didn't do it because not everytime time we'll injecting script with src, sometime it could be multiline javascript code itself.
that's why I leave it to dev to write script however they want and they can pass it to `simpl_inject_script` to get the necessary things done on the script to be inject, today it's just attributes tomorrow method could be more matured.

2023-10-22 11:34 UTC, piyush-getsimpl commented on includes/helpers/script_helper.php
> +  		$attrs = ' ';
`$attrs = implode(" ", SCRIPT_ATTRIBUTES)`

Don't need the for loop.

2023-10-22 12:53 UTC, Chhekur commented on includes/helpers/script_helper.php
> +  		$attrs = ' ';
done, I wasn't aware about this.

2023-10-25 08:19 UTC, rithiksharma100 requested changes

2023-10-25 08:19 UTC, rithiksharma100 commented on includes/endpoints/public/master-config.php
> +		simpl_inject_script('<script {{attributes}} type="text/javascript">var SimplMasterConfig = ' . $masterConfigData . '</script>');
we have to use wordpress native methods to inject scripts instead of using `echo`

2023-10-25 08:28 UTC, Chhekur commented on includes/endpoints/public/master-config.php
> +		simpl_inject_script('<script {{attributes}} type="text/javascript">var SimplMasterConfig = ' . $masterConfigData . '</script>');
I don't think possible to wordpress native method to use here since we want to override script tag attributes itself which I don't see the native method allow, it just ask for script and attach rest by itself.

2023-10-25 08:29 UTC, rithiksharma100 commented on includes/endpoints/public/master-config.php
> +		simpl_inject_script('<script {{attributes}} type="text/javascript">var SimplMasterConfig = ' . $masterConfigData . '</script>');
this syntax won't pass the plugin review for making it public

2023-10-25 08:31 UTC, Chhekur commented on includes/endpoints/public/master-config.php
> +		simpl_inject_script('<script {{attributes}} type="text/javascript">var SimplMasterConfig = ' . $masterConfigData . '</script>');
I don't think wordpress had comment on this before as well?

2023-10-25 10:58 UTC, rithiksharma100 approved these changes

2023-10-25 11:00 UTC, merged