[Order] Add: Support for simpl exclusive discount
GetSimpl/simpl-checkout-woocommerce pull request #139
Opened 2023-10-27 14:53 UTC by Chhekur

2023-10-30 06:32 UTC, abhaymaniyar commented on includes/helpers/class-simpl-wc-helper.php
> +                if ($discount['type'] == SIMPL_EXCLUSIVE_DISCOUNT) {
We can invert this condition and do early return for better readability.

2023-10-30 06:32 UTC, abhaymaniyar commented on includes/helpers/class-simpl-wc-helper.php
> +        if ($applied_discounts) {
We can invert this condition and do early return for better readability.

2023-10-30 06:32 UTC, abhaymaniyar commented on includes/helpers/class-simpl-wc-helper.php
> +const SIMPL_EXCLUSIVE_DISCOUNT = 'simpl_exclusive';
> 
> 
> const vs. define()
> 
>     const are always case-sensitive
>     define() has has a case-insensitive option.
>     const cannot be created inside another block scope, like inside a function or inside an if statement.
>     define can be created inside another block scope.
> 
> 

The top two points in this blog snippet should be considered before using const.

2023-10-30 07:35 UTC, Chhekur commented on includes/helpers/class-simpl-wc-helper.php
> +                if ($discount['type'] == SIMPL_EXCLUSIVE_DISCOUNT) {
sure, will update.

2023-10-30 07:35 UTC, Chhekur commented on includes/helpers/class-simpl-wc-helper.php
> +const SIMPL_EXCLUSIVE_DISCOUNT = 'simpl_exclusive';
yes, this should be case sensitive only.

2023-10-30 08:33 UTC, rithiksharma100 requested changes

2023-10-30 08:33 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +                    $order->set_total($order->get_total() - $discount['amount']);
we shouldn't set totals manually, instead we can do `$order->calculate_totals()` that does all this natively

2023-10-30 08:33 UTC, rithiksharma100 commented on simpl-checkout-woocommerce.php
> + * Version: 1.2.5
version update

2023-10-30 08:48 UTC, Chhekur commented on includes/helpers/class-simpl-wc-helper.php
> +                    $order->set_total($order->get_total() - $discount['amount']);
here since we are not creating the coupon directly creating the order_item, so calling `calculate_totals` on order won't have any impact, that's why we are doing the calculation manually.

2023-10-30 09:39 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +                    $order->set_total($order->get_total() - $discount['amount']);
Oh, why aren't we creating an order_item?

2023-10-30 09:43 UTC, Chhekur commented on includes/helpers/class-simpl-wc-helper.php
> +                    $order->set_total($order->get_total() - $discount['amount']);
no we are creating order_item only, we are not creating coupon.

2023-10-30 10:58 UTC, Chhekur commented on includes/helpers/class-simpl-wc-helper.php
> +                    $order->set_total($order->get_total() - $discount['amount']);
I've tried this as well, this also works only if coupon exists in the system.

2023-10-30 11:00 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +                    $order->set_total($order->get_total() - $discount['amount']);
No it works either way, I just tried

2023-11-07 08:21 UTC, rithiksharma100 requested changes

2023-11-07 08:21 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +            $coupon->set_discount(wc_format_decimal($discount['amount'] / 100, 2)); // converting it to rupees
we decided as a standard when building 3pp that all amount conversions will happen at checkout-3pp level, and no paise rupee conversion logic should exist in the plugin

2023-11-07 08:21 UTC, rithiksharma100 commented on includes/helpers/class-simpl-wc-helper.php
> +            $order->recalculate_coupons();
order->save() should happen after recalculate_coupons() right?

2023-11-08 13:58 UTC, piyush-getsimpl commented on includes/helpers/class-simpl-wc-helper.php
> +            $coupon->set_discount(wc_format_decimal($discount['amount'] / 100, 2)); // converting it to rupees
Lets handle it in 3pp then to keep it consistent - all platform interactions happen in rupee

2023-11-08 14:54 UTC, Chhekur commented on includes/helpers/class-simpl-wc-helper.php
> +            $order->recalculate_coupons();
I tried that but wasn't working.

2023-11-08 16:42 UTC, Chhekur commented on includes/helpers/class-simpl-wc-helper.php
> +            $coupon->set_discount(wc_format_decimal($discount['amount'] / 100, 2)); // converting it to rupees
Done

2023-11-09 11:04 UTC, rithiksharma100 submitted a review, later dismissed

2023-11-10 11:34 UTC, rithiksharma100 submitted a review, later dismissed

2023-11-10 11:38 UTC, abhaymaniyar approved these changes

2023-11-10 11:38 UTC, merged