Changes for plugin deactivate event
GetSimpl/simpl-checkout-woocommerce pull request #85
Opened 2023-06-01 05:00 UTC by saurabhsingh-simpl

On plugin deactivation an event will be published
Sample Event :
` 
{
   "entity": "Manage Plugin",
   "event_data": {
      "action": "plugin deactivate",
      "email": "saurabh.singh@getsimpl.com",
      "merchant_id": "checkout-3pp.stagingsimpl.com",
      "user": "admin"
   },
   "event_id": "7b397e56-0d79-4cea-89a2-15247b5669aa",
   "event_name": "Update Plugin",
   "event_namespace": "checkout_3pp",
   "event_timestamp": "2023-05-26 10:21:10.460411",
   "event_type": "Admin::Events",
   "flow": "woocommerce-admin plugin page",
   "origin": {
      "service": "woocommerce-backend",
      "squad": "checkout-3pp"
   },
   "trigger_timestamp": 1685340551,
   "version": "1.0.0"
}`

2023-06-01 06:01 UTC, sathia27 requested changes

2023-06-01 06:01 UTC, sathia27 commented on includes/helpers/class-simpl-wc-helper.php
> +                    "content-type" => "application/json"
client_id, client_secret, shop_domain have to be sent. so that validation will happen.

2023-07-13 08:16 UTC, saurabhsingh-simpl commented on includes/helpers/class-simpl-wc-helper.php
> +                    "content-type" => "application/json"
https://simpl.atlassian.net/browse/CHECK-2890
added tech debt task to add validation, currently publish event endpoint has no check

2023-07-17 06:31 UTC, rithiksharma100 approved these changes

2023-07-18 05:12 UTC, merged