State Validation Fix
GetSimpl/simpl-checkout-woocommerce pull request #97
Opened 2023-08-30 11:08 UTC by rithiksharma100

Bug: Getting state is not supported error on the iframe for the user login flow as checkout gets created without state.
Fix: Removed state to state-code conversion if it is empty

2023-08-30 13:51 UTC, sathia27 requested changes

2023-08-30 13:51 UTC, sathia27 commented on includes/simpl_integration/class-cart-response.php
> +            if(!isset($state)) {
won't this return empty? din't we need empty check here as well.

2023-08-30 13:51 UTC, sathia27 commented on includes/simpl_integration/class-cart-response.php
> +        if(isset($address["state"]) && $address["state"] != "") {
instead of `isset` can we use `empty`. i guess `empty` checks both null and empty string

2023-08-31 04:30 UTC, rithiksharma100 commented on includes/simpl_integration/class-cart-response.php
> +        if(isset($address["state"]) && $address["state"] != "") {
sure

2023-08-31 05:53 UTC, rithiksharma100 commented on includes/simpl_integration/class-cart-response.php
> +        if(isset($address["state"]) && $address["state"] != "") {
done

2023-08-31 05:56 UTC, rithiksharma100 commented on includes/simpl_integration/class-cart-response.php
> +            if(!isset($state)) {
added

2023-08-31 08:02 UTC, sahil-simpl approved these changes

2023-09-05 14:25 UTC, sathia27 approved these changes

2023-09-05 14:25 UTC, merged