feat: add api to fetch bulk refunds
GetSimpl/simpl-checkout-woocommerce pull request #98
Opened 2023-08-30 12:21 UTC by abhaymaniyar

2023-09-01 05:29 UTC, sathia27 commented on includes/endpoints/internal/class-simpl-checkout-order-controller.php
> +    function fetch_refund_orders(WP_REST_Request $request) {
Is it necessary to develop a batch job within the plugin? Personally, I'd prefer to avoid it. WooCommerce doesn't scale as flexibly as our apps do. We could manage aspects like throttling and other mechanisms on our side. Instead, can we retrieve refund information on a per-order basis? checkout-3pp can handle the orchestration to aggregate data in bulk. What are your thoughts on this approach?

2023-09-01 05:30 UTC, sathia27 commented on includes/endpoints/internal/class-simpl-checkout-order-controller.php
> +    function fetch_refund_orders(WP_REST_Request $request) {
If we were to send multiple order IDs in a single API request, there's a risk that if the API crashes due to memory issues, it could potentially bring down the entire website.

2023-09-28 08:33 UTC, Chhekur requested changes

2023-09-28 08:33 UTC, Chhekur commented on simpl-checkout-woocommerce.php
> +    add_action( 'woocommerce_order_refunded', 'order_hook', 10, 1 );
let's not write webhook directly into this file, since tomorrow we might need to support webhooks also so it's better to the directory as `webhooks` similar to endpoints.

2023-09-28 08:33 UTC, Chhekur commented on simpl-checkout-woocommerce.php
> +function order_hook($order_id)
same method defination should go under the webhooks.

2023-09-28 08:33 UTC, Chhekur commented on simpl-checkout-woocommerce.php
> +    $client_credentials = WC_Simpl_Settings::merchant_credentials();
we shouldn't fetch this info everywhere we make API calls to simpl server, ideally should be fetched at centralized places similar to we have clients implementation in other go repos.

2023-09-28 08:33 UTC, Chhekur commented on simpl-checkout-woocommerce.php
> +    $order_data["date_paid"] = convert_date_obj_to_str($order->get_date_paid());
wouldn't it automatically transform while making the HTTP call?

2023-09-28 08:33 UTC, Chhekur commented on simpl-checkout-woocommerce.php
> +    $order_data["date_completed"] = convert_date_obj_to_str($order->get_date_completed());
same^

2023-09-28 08:33 UTC, Chhekur commented on simpl-checkout-woocommerce.php
> +            WEBHOOK_EVENT => "updated",
should we define these into headers, or should we go with the body itself?
since this is not something like credential info or secret info, thoughts?

2023-09-28 08:33 UTC, Chhekur commented on simpl-checkout-woocommerce.php
> +    $simplHttpResponse = wp_remote_post("https://" . $simpl_host . "/order_hook", array(
I belive we should define the client layer so that we don't have to repeat ourselves for the same thing.

2023-09-28 08:33 UTC, Chhekur commented on simpl-checkout-woocommerce.php
> +    $simplHttpResponse = wp_remote_post("https://" . $simpl_host . "/order_hook", array(
why do we have a separate route for this webhook, ideally we can just have one endpoint from out 3pp service and we can route all the webhooks to the same endpoint from the plugin and based on the params service can take the decisions, thoughts?

2023-09-28 08:33 UTC, Chhekur commented on simpl-checkout-woocommerce.php
> +function get_order_line_items($order) {
why do we need these supporting methods, wouldn't `$order->get_data()` give the whole order data?

2023-09-28 11:28 UTC, abhaymaniyar commented on simpl-checkout-woocommerce.php
> +            WEBHOOK_EVENT => "updated",
Noted. Can be sent in the body.

2023-09-28 11:29 UTC, abhaymaniyar commented on simpl-checkout-woocommerce.php
> +    $simplHttpResponse = wp_remote_post("https://" . $simpl_host . "/order_hook", array(
Noted.

2023-09-28 11:29 UTC, abhaymaniyar commented on simpl-checkout-woocommerce.php
> +    $simplHttpResponse = wp_remote_post("https://" . $simpl_host . "/order_hook", array(
Noted. Will create a generic hook endpoint.

2023-09-28 11:29 UTC, abhaymaniyar commented on simpl-checkout-woocommerce.php
> +function get_order_line_items($order) {
Noted. Will move all parsing methods/logic to 3pp.

2023-10-03 05:37 UTC, rithiksharma100 requested changes

2023-10-03 05:37 UTC, rithiksharma100 commented on simpl-checkout-woocommerce.php
> +function hook($order_id)
should change the function name, this is very generic, might create conflicts

2023-10-03 05:37 UTC, rithiksharma100 commented on simpl-checkout-woocommerce.php
> +function hook($order_id)
This file should only contain init logic, we can create a separate file for the refund hook

2023-10-03 05:40 UTC, rithiksharma100 requested changes

2023-10-03 05:40 UTC, rithiksharma100 commented on includes/clients/checkout-3pp-client.php
> +        define('WEBHOOK_SOURCE', 'X-WC-Webhook-Source');
do we need these webhook headers now as we've created a separate endpoint for refund hook?

2023-10-03 05:47 UTC, abhaymaniyar commented on includes/clients/checkout-3pp-client.php
> +class Simpl_Checkout_3pp_Client {
Noted

2023-10-03 05:47 UTC, abhaymaniyar commented on includes/clients/checkout-3pp-client.php
> +        define('WEBHOOK_SOURCE', 'X-WC-Webhook-Source');
We pass these values to the event we raise so I was thinking of keeping this part same for the new endpoint as well.

2023-10-03 05:47 UTC, abhaymaniyar commented on simpl-checkout-woocommerce.php
> +function hook($order_id)
Changing the function name to order_hook. Also, keeping the init logic here for now since that's how we are doing at other places in this repo.

2023-10-03 12:29 UTC, Chhekur commented on includes/clients/checkout-3pp-client.php
> +        define('WEBHOOK_EVENT', 'X-WC-Webhook-Event');
are we using these?

2023-10-04 13:18 UTC, Chhekur commented on includes/hook_handlers/order-hook-handler.php
> +    $simpl_host = WC_Simpl_Settings::simpl_host();
let's not pass these creds to the client, let the client constructor fetch it, since these configs are not dynamic.

2023-10-04 13:18 UTC, Chhekur commented on includes/clients/checkout-3pp-client.php
> +    function simpl_post_hook_request($request) {
let's just check the method name do we really need simpl as prefix here since this method is already in the scope of `SimplCheckout3ppClient`?

2023-10-05 09:06 UTC, Chhekur approved these changes
LGTM!

2023-10-05 11:28 UTC, Chhekur submitted a review, later dismissed

2023-10-05 11:47 UTC, rithiksharma100 approved these changes
Rebase with main once, version has been updated

2023-10-05 12:14 UTC, Chhekur approved these changes

2023-10-05 12:15 UTC, merged